# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b69ff785d0e4c681aac8ed0b74e568c0965e4a15ffbcb3314d49d5ee137a2429410d47bcea6647cfdc6132f58c2c7db53e22db7cca4eae64e15e2c053990be1e

test:
  secret_key_base: 5e9a323d01888a9b38163a045e4e0d3d52678ff6cb9b99c173c8e9b3c912cdcb8d005324ad2027be812321afbb5cee6b7785a17c3d2dbf4c71ee2967bbd59a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
